# Generated by Django 5.2.4 on 2025-07-31 23:01

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_mob',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=15, region=None, unique=True, verbose_name='Мобильный телефон'),
        ),
    ]
